project:
  type: website
  output-dir: docs
  
website:
  title: ""
  favicon: "bcem-logo.png"

  navbar:
    logo: "bcem-logo.png"
    collapse-below: md
    right:
      - href: index.qmd
        text: "{{< fa house >}} Home"

      - href: people.qmd
        text: "{{< fa people-group >}} People"

      - href: research.qmd
        text: "{{< fa microscope >}} Research"

      - href: publications.qmd
        text: "{{< fa scroll >}} Publications"

      # - href: resources.qmd
      #   text: Resources

      # - href: oportunities.qmd
      #   text: Oportunities # Data and Tools

      - href: contact.qmd
        text: "{{< fa paper-plane >}} Contact"

      # - href: collaborators.qmd
      #   text: Collaborators


  back-to-top-navigation: true

  page-footer: 
    center: " © 2023, BCEM - Universidad de Los Andes" 
    right: "Vigilada Mineducación" 
    left: "Powered by Quarto. Done with {{< fa heart >}}"
    background: light

format:
  html:
    theme:
      light:
        - sandstone # -  yeti #sandstone #pulse #sketchy #vapor #cosmo

css: styles.css